name: Fuzz

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version'
        required: true
        type: string
      fuzztime:
        description: 'the time to fuzz for'
        required: true
        default: '60s'
        type: string

jobs:
  keystore:
    name: keystore fuzz
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: fuzz/lib/keystore
        working-dir: tests/fuzz
        run: |
          go test -fuzz=FuzzKeyStoreName -fuzztime ${{ inputs.fuzztime }} ./lib/keystore

      - name: Upload Fuzz Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: keystore-fuzz-artifacts
          path: tests/fuzz/lib/keystore/testdata/fuzz/*

      - name: Output message
        if: failure()
        shell: bash
        run: |
          echo -e "lib/keystore fuzz testing failed on commit ${{ env.SHA }}."
          echo "download failing seed corpus from ${{ github.run_id }} artifacts/lib-keystore-fuzz-corpus"
          echo "add to project at tests/fuzz/lib/keystore/testdata/fuzz"

  reverse:
    name: util/lib/reverse fuzz
    runs-on: ubuntu-latest
    outputs:
      failed: ${{ steps.status.outputs.status }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: lib/utils/reverse
        id: fuzz
        working-dir: tests/fuzz
        run: |
          go test -fuzz=FuzzReverse -fuzztime ${{ inputs.fuzztime }} ./lib/utils/reverse

      - name: Upload Fuzz Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: keystore-fuzz-artifacts
          path: tests/fuzz/lib/keystore/testdata/fuzz/*

      - name: Output message on failure
        if: failure()
        run: |
          echo "Reverse fuzz testing failed on commit $GITHUB_SHA."
          echo "Failing seed corpus will be added to the merged artifacts."

  number:
    name: trivial number fuzz
    runs-on: ubuntu-latest
    outputs:
      failed: ${{ steps.fuzz.outputs.status }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: lib/util//number
        id: fuzz
        working-dir: tests/fuzz
        run: |
          go test -fuzz=FuzzProcessNumber -fuzztime ${{ inputs.fuzztime }} ./lib/utils/number

      - name: Upload Fuzz Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: number-fuzz-artifacts
          path: tests/fuzz/lib/utils/number/testdata/fuzz/*

      - name: Output message on failure
        if: failure()
        run: |
          echo "utils/number/dummy fuzz testing failed on commit $GITHUB_SHA."
          echo "Failing seed corpus will be added to the merged artifacts."


