name: pull request verification

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - name: require label
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "kind:fix, kind:misc, kind:break!, kind:refactor, kind:feat, kind:deps, kind:docs, kind:ci, kind:chore, kind:testing" # yamllint disable-line rule:line-length

      - name: verify referenced issue
        uses: ramin/verify-linked-issue-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
