name: Go Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  SKIP_CI: TRUE

jobs:
  test_coverage:
    name: Unit Tests Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17"]
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test & Coverage
        run: |
          go install github.com/ory/go-acc@v0.2.6
          go-acc -o coverage.txt `go list ./... | grep -v node/tests` -- -v
      - uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.txt
  unit_race_test:
    name: Run All Unit Tests with Race Detector (No Core)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17"]
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: execute test run
        run: make SKIP_CI=${{ env.SKIP_CI }} test-unit-race
  unit_core_race_test:
    name: Run Core Unit Tests with Race Detector
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17"]
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: execute test run
        run: go test -v -race -tags test_unit_core ./...
  integration_test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17"]
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Swamp Tests
        run: make test-swamp
      - name: Swamp Tests with Race Detector
        run: make test-swamp-race
