name: Go Vet Fmt Test

on:
  push:
    branches: 
      - main
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.0'

    - name: vet
      run: go vet -v ./...

    - name: fmt
      run: gofmt -s -l .

    - name: test
      run: go test -v ./...
